# To regenerate the resources run; kustomize edit add resource config/*.yaml
resources:
- config/100-namespace.yaml
- config/200-serviceaccount.yaml
- config/201-clusterrole.yaml
- config/202-clusterrolebinding.yaml
- config/300-kafkasource.yaml
- config/400-controller-service.yaml
- config/500-controller.yaml
patchesJson6902:
- path: overlays/openshift-privs.yaml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: eventing-sources-kafka-controller
    version: v1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
